---
# Certbot
certbot_auth_method: --webroot
certbot_well_known_root: /srv/nginx/_well-known_root
certbot_share_key_users:
  - nginx
certbot_virtualenv_command: virtualenv-3.6
certbot_virtualenv_package_name: python3-virtualenv
certbot_post_renewal: |
    systemctl restart nginx || true

# NGINX
nginx_enable_default_server: false
nginx_servers:
  - redirect-ssl
nginx_ssl_servers:
  - grafana-ssl

nginx_conf_http:
  gzip: "on"
  gzip_vary: "on"
  gzip_min_length: 256
  gzip_proxied: any
  gzip_comp_level: 6
  gzip_http_version: "1.1"
  gzip_types: text/plain text/css text/xml text/javascript application/javascript application/x-javascript application/xml image/png image/jpg
  gzip_disable: '"MSIE [1-6]\."'
  client_max_body_size: 1g

nginx_remove_default_vhost: true

# Nginx Letsencrypt bindings
nginx_ssl_role: usegalaxy-eu.certbot
nginx_conf_ssl_certificate: /etc/ssl/certs/fullchain.pem
nginx_conf_ssl_certificate_key: /etc/ssl/user/privkey-nginx.pem

# Grafana
grafana_data_dir: /data/monitoring/grafana_data
grafana_instance: "{{ hostname }}"
grafana_address: "127.0.0.1"
grafana_url: "https://stats.galaxyproject.eu"
grafana_server:
  domain: "{{ hostname }}"
  root_url: "https://%(domain)s/"

grafana_users:
  default_theme: "light"

grafana_security:
  admin_user: admin
  admin_password: "{{ grafana_auth_admin_password }}"
  allow_embedding: "true"
  cookie_secure: "true"

grafana_auth:
  anonymous:
    enabled: "true"
    org_name: "UseGalaxy.eu"
    org_role: "Viewer"

  github:
    enabled: "true"
    allow_sign_up: "true"
    client_id: "{{ grafana_auth__github_client_id }}"
    client_secret: "{{ grafana_auth__github_client_secret }}"
    scopes: "user:email,read:org"
    auth_url: "https://github.com/login/oauth/authorize"
    token_url: "https://github.com/login/oauth/access_token"
    api_url: "https://api.github.com/user"
    allowed_organisations: "usegalaxy.eu galaxyproject"

grafana_image_storage:
  provider: local

grafana_environment:
  GF_PANELS_DISABLE_SANITIZE_HTML: 'true'

grafana_plugins:
  - grafana-worldmap-panel
  - grafana-piechart-panel
  - natel-discrete-panel

grafana_datasources:
  - name: Galaxy
    type: influxdb
    access: proxy
    url: "{{ influxdb.url }}"
    isDefault: true
    version: 1
    editable: false
    database: galaxy
    user: "{{ influxdb.grafana.username }}"
    secureJsonData:
      password: "{{ influxdb.grafana.password }}"
  - name: Galaxy Historical
    type: influxdb
    access: proxy
    url: "{{ influxdb.url }}"
    version: 1
    editable: false
    database: galaxy_stats
    user: "{{ influxdb.grafana.username }}"
    secureJsonData:
      password: "{{ influxdb.grafana.password }}"
  - name: GRT Tool Usage
    type: influxdb
    access: proxy
    url: "{{ influxdb.url }}"
    version: 1
    editable: false
    database: grt
    user: "{{ influxdb.grafana.username }}"
    secureJsonData:
      password: "{{ influxdb.grafana.password }}"
  - name: InfluxDB - internal
    type: influxdb
    access: proxy
    url: "{{ influxdb.url }}"
    version: 1
    editable: false
    database: _internal
    user: "{{ influxdb.grafana.username }}"
    secureJsonData:
      password: "{{ influxdb.grafana.password }}"
  - name: Notifications
    type: influxdb
    access: proxy
    url: "{{ influxdb.url }}"
    version: 1
    editable: false
    database: notifications
    user: "{{ influxdb.grafana.username }}"
    secureJsonData:
      password: "{{ influxdb.grafana.password }}"

hxr_monitor_ssl_expiry:
  # A couple of usegalaxy.eu subdomains.
  - usegalaxy.eu:443
  - metagenomics.usegalaxy.eu:443
  # Proxy + Proxied services
  - build.galaxyproject.eu:443
  - influxdb.galaxyproject.eu:8086
  - influxdb.galaxyproject.eu:443
  - stats.galaxyproject.eu:443
  - telescope.galaxyproject.eu:443
  - toolshed.g2.bx.psu.edu:443
  - galaxyproject.org:443
  - usegalaxy.org:443


telegraf_plugins_extra:
  github:
    plugin: github
    config:
      - repositories = ["galaxyproject/galaxy", "galaxyproject/training-material", "usegalaxy-eu/gxadmin"]
      - interval = "6h"
  simple_nagios:
    plugin: "exec"
    config:
      - commands = ["/usr/bin/simple-nagios"]
      - timeout = "120s"
      - data_format = "influx"
      - interval = "1m"

  #galaxy_jobs:
    #plugin: "exec"
    #config:
      #- commands = ["/usr/local/bin/simple-galaxy"]
      #- timeout = "180s"
      #- data_format = "influx"
      #- interval = "15m"

#galaxy_test_url: https://usegalaxy.eu
#galaxy_test_user:
    #api_key: "{{ galaxy_test_user__api_key }}"
    #username: bot@usegalaxy.eu
    #password: "{{ galaxy_test_user__password }}"
    #handlers:
        #- "handler0"
        #- "handler1"
        #- "handler2"
        #- "handler3"
        #- "handler4"
        #- "handler5"
        #- "handler6"
        #- "handler7"
        #- "handler8"
        #- "handler9"
        #- "handler10"
        #- "handler11"
        #- "drmaa"
        #- "condor"

galaxy_nagios_urls:
  ftp_tests: []
  http_tests:
    - name: home_nossl
      url: "http://usegalaxy.eu"
      code: 301
    - name: home
      url: "https://usegalaxy.eu"
      code: 200
    - name: hicexplorer
      url: "https://hicexplorer.usegalaxy.eu"
      code: 200
    - name: stats
      url: "https://stats.galaxyproject.eu"
      code: 200
    - name: grt
      url: "https://telescope.galaxyproject.eu"
      code: 200
    - name: build
      url: "https://build.galaxyproject.eu"
      code: 200
    - name: influx
      url: "{{ influxdb.url }}/ping"
      code: 204
    - name: phinch
      url: "https://usegalaxy.eu/phinch/index.html"
      code: 200

matrix_forwarder_resolve_mode: reaction
