annotation:
  masthead:
    color: >
      linear-gradient(to right, #3337 0, #3337 365px, transparent 365px),
      linear-gradient(to left, #3337 0, #3337 120px, transparent 120px),
      left / 23% url("/static/dist/annotation.png")
    link:
      color: "#3337"
      hover: "#3339"
      active: "#333e"
