assembly:
  masthead:
    color: >
      bottom -90px left / 1000px no-repeat url("/static/dist/flying-bird-1.svg"),
      bottom -90px left / 1000px no-repeat url("/static/dist/flying-bird-2.svg"),
      linear-gradient( 20deg,
        rgb(7, 40, 98) 0%,
        rgb(69, 122, 184) 48%,
        rgba(165, 204, 210, 0.9676562309265136) 74%,
        rgb(228, 195, 131) 92%,
        rgb(203, 119, 79) 100%)
