hicexplorer:
  masthead:
    color: >
      linear-gradient(to right, #3337 0, #3337 285px, transparent 285px),
      linear-gradient(to left, #3337 0, #3337 120px, transparent 120px),
      left / 340px url("/static/dist/hicexplorer.png")
    link:
      color: "#3337"
      hover: "#3339"
      active: "#333e"
