imaging:
  masthead:
    color: >
      linear-gradient(90deg,
        rgb(0, 0, 0) 0%,
        rgb(0, 69, 227) 17%,
        rgb(9, 121, 33) 30%,
        rgb(180, 170, 15) 70%,
        rgb(193, 35, 0) 79%,
        rgb(0, 0, 0) 100%)
