virology:
  masthead:
    color: >
      linear-gradient(50deg,
        hsl(240deg 100% 20%) 0%,
        hsl(234deg 95% 23%) 13%,
        hsl(227deg 90% 26%) 26%,
        hsl(220deg 85% 29%) 38%,
        hsl(213deg 79% 32%) 52%,
        hsl(207deg 74% 35%) 66%,
        hsl(200deg 69% 38%) 82%,
        hsl(194deg 64% 42%) 100%)
