---
galaxy_info:
  author: The Galaxy Project
  description: Installs a Galaxy rsync script
  company: The Galaxy Project
  license: AFL v3.0
  min_ansible_version: 2.5
  platforms:
  - name: EL
    versions:
    - 8
    - 9
  galaxy_tags: []
dependencies: []
