pgc_users:
  - uname: "{{ galaxy_user.name }}"
    uhome: "{{ galaxy_user.home }}"
    gname: "{{ galaxy_group.name | default(galaxy_group) }}"
    pguser: "{{ postgres_user }}"
    pgpass: "{{ postgres_pass }}"
    pgdatabase: galaxy
