---
- name: Get all users
  getent:
    database: passwd
    split: ':'

- name: Debug info when user does not exist
  debug:
    msg: "INFO: User {{ item.uname }} does not exist"
  loop: "{{ pgc_users }}"
  when: (not item.uname in getent_passwd.keys())

- name: Run postgres tasks
  include_tasks: postgres_tasks.yml
  loop: "{{ pgc_users }}"
  when: (item.uname in getent_passwd.keys())
